name: CI
env:
  MIDNIGHTCI_PACKAGES_WRITE: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"

permissions:
  contents: read
  issues: read
  id-token: write
  packages: write
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Build, Lint and Test
    uses: ./.github/workflows/ci-base.yaml
    with:
      coverage-files: |
        compact-js, ./compact-js/coverage/coverage-summary.json
        compact-js-command, ./compact-js-command/coverage/coverage-summary.json
        compact-js-node, ./compact-js-node/coverage/coverage-summary.json
    secrets: inherit
